Softeq/XToolkit.WhiteLabel

Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardDialogsService.cs, Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj, Softeq.XToolkit.WhiteLabel/Mvvm/DialogViewModelBase.cs, Softeq.XToolkit.WhiteLabel/Mvvm/DialogViewModelComponent.cs, Softeq.XToolkit.WhiteLabel/Navigation/IDialogsService.cs, Softeq.XToolkit.WhiteLabel/Navigation/NavigationHelpers/DialogNavigationHelper.cs, Softeq.XToolkit.WhiteLabel/Services/Logger/ConsoleLogManager.cs, Softeq.XToolkit.WhiteLabel/Services/Logger/ConsoleLogger.cs
**To navigate without parameter we will use** 
_dialogService.ShowForViewModel<IViewmodel, TResult>()
**To Navigate with parameters we will use** 
_dialogService.For<IViewModel>().WithParam<>().Navigate<TResult>()
**To navigate without result use**
_dialogService.ShowForViewModel<IViewModel>(); or _dialogService.For<IViewmodel>().WithParam(x=>x.Parameter, value).Navigate(); or _dialogService.For<IViewmodel>().Navigate()
=> Dialog improvements

Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DialogFragmentBase.cs, Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DroidFragmentDialogService.cs, Softeq.XToolkit.WhiteLabel.Droid/Navigation/FrameNavigationService.cs, Softeq.XToolkit.WhiteLabel.Droid/Navigation/ViewLocator.cs, Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj, Softeq.XToolkit.WhiteLabel/Navigation/NavigationHelpers/DialogNavigationHelper.cs
Reverts Softeq/XToolkit.WhiteLabel#45
=> Revert "Navigation changes partially implemented on Android"

Softeq.XToolkit.Permissions.Droid/PermissionsManager.cs, Softeq.XToolkit.Permissions.Droid/PermissionsService.cs, Softeq.XToolkit.Permissions.iOS/PermissionsManager.cs, Softeq.XToolkit.Permissions.iOS/PermissionsService.cs, Softeq.XToolkit.Permissions/Permission.cs
- Add more permissions
- Code clean up
=> Permissions

Softeq.XToolkit.Bindings/PropertyChangedEventManager.cs
=> improved bindings

Softeq.XToolkit.Permissions/NotificationsPermission.cs, Softeq.XToolkit.WhiteLabel.Droid/ImagePicker/DroidImagePickerResult.cs, Softeq.XToolkit.WhiteLabel.Droid/ImagePicker/DroidImagePickerService.cs, Softeq.XToolkit.WhiteLabel.Droid/ImagePicker/ImagePickerActivity.cs, Softeq.XToolkit.WhiteLabel.iOS/ImagePicker/ImagePicker.cs, Softeq.XToolkit.WhiteLabel.iOS/ImagePicker/IosImagePickerResult.cs, Softeq.XToolkit.WhiteLabel.iOS/ImagePicker/IosImagePickerService.cs, Softeq.XToolkit.WhiteLabel/ImagePicker/IImagePickerService.cs, Softeq.XToolkit.WhiteLabel/ImagePicker/ImageExtensionToStringConverter.cs, Softeq.XToolkit.WhiteLabel/ImagePicker/ImagePickerArgs.cs, Softeq.XToolkit.WhiteLabel/ImagePicker/ImagePickerResult.cs, Softeq.XToolkit.WhiteLabel/Navigation/FluentNavigators/FrameFluentNavigator.cs, samples/Playground/Playground.Droid/Views/Pages/PermissionsPageActivity.cs, samples/Playground/Playground.iOS/LinkerPleaseInclude.cs, samples/Playground/Playground.iOS/ViewControllers/Pages/PermissionsPageViewController.cs, samples/Playground/Playground/ViewModels/Pages/PermissionsPageViewModel.cs
Fixed:
- Crash when Camera canceled
- Handle recreation ImagePickerActivity by the system
Also: 
- Added some comments
=> Droid imagepicker improves

Softeq.XToolkit.WhiteLabel.iOS/Interfaces/IViewControllerProvider.cs, Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardViewLocator.cs, Softeq.XToolkit.WhiteLabel.iOS/Services/ViewControllerProvider.cs
=> Fix getting top ViewController from TabBar ViewControllers

Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DroidFragmentDialogService.cs, Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardDialogsService.cs, Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj, Softeq.XToolkit.WhiteLabel.iOS/ViewControllers/TopLevelAlertController.cs, Softeq.XToolkit.WhiteLabel/Model/OpenDialogOptions.cs, Softeq.XToolkit.WhiteLabel/Navigation/IDialogsService.cs, samples/Playground/Playground/ViewModels/Pages/CollectionPageViewModel.cs
=> [iOS] Show Alert on the Top Level

Softeq.XToolkit.Bindings.iOS/ObservableGroupTableViewSource.cs, Softeq.XToolkit.Common/Collections/ObservableKeyGroupsCollection.cs
=> [iOS] Improve notify ObservableGroupTableViewSource

Softeq.XToolkit.Bindings.iOS/ObservableGroupTableViewSource.cs, Softeq.XToolkit.WhiteLabel.iOS/Helpers/UiTabBarControllerHelper.cs, Softeq.XToolkit.WhiteLabel.iOS/Navigation/RootFrameNavigationControllerBase.cs, Softeq.XToolkit.WhiteLabel.iOS/ViewControllers/ToolbarViewControllerBase.cs
=> various improvements

Softeq.XToolkit.WhiteLabel/Softeq.XToolkit.WhiteLabel.csproj
The purpose is that all NuGet packages versions match in our current projects
=> Newtonsoft.Json updated

samples/Playground/Playground.Droid/Playground.Droid.csproj, samples/Playground/Playground.Droid/Resources/layout/activity_empty.xml, samples/Playground/Playground.Droid/Resources/menu/main.xml, samples/Playground/Playground.Droid/Views/EmptyPageActivity.cs, samples/Playground/Playground.Droid/Views/MainPageActivity.cs, samples/Playground/Playground.iOS/Playground.iOS.csproj, samples/Playground/Playground.iOS/ViewControllers/EmptyPageStoryboard.storyboard, samples/Playground/Playground.iOS/ViewControllers/EmptyPageViewController.cs, samples/Playground/Playground.iOS/ViewControllers/EmptyPageViewController.designer.cs, samples/Playground/Playground.iOS/ViewControllers/MainPageViewController.cs, samples/Playground/Playground/ViewModels/EmptyPageViewModel.cs, samples/Playground/Playground/ViewModels/MainPageViewModel.cs
An empty page for playing, samples and others what you want to test on your projects.
=> [Playground] Add empty page

Softeq.XToolkit.Common.Tests/Collections/ObservableKeyGroupsCollectionNew/ObservableKeyGroupsCollectionNewTests.cs, Softeq.XToolkit.Common.Tests/Softeq.XToolkit.Common.Tests.csproj, Softeq.XToolkit.Common/Collections/ObservableKeyGroupsCollectionNew.cs, Softeq.XToolkit.Common/EventArguments/NotifyKeyGroupCollectionChangedEventArgs.cs, Softeq.XToolkit.Common/Extensions/EnumerablesExtensions.cs, Softeq.XToolkit.Common/Interfaces/INotifyKeyGroupCollectionChanged.cs, Softeq.XToolkit.Common/Interfaces/IObservableKeyGroupCollection.cs, Softeq.XToolkit.Common/Interfaces/IObservableKeyGroupsCollection.cs
=> Keygroup collection

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, documentation/articles/contributing-workflow.md, documentation/articles/contributing.md, documentation/articles/developer-guide.md
Guides & templates based on:
- [dotnet/coreclr](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md)
- [dotnet/corefx](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md)
- [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/tree/master/.github)
=> Contribution guides

Softeq.XToolkit.WhiteLabel/Services/JsonSerializer.cs, Softeq.XToolkit.WhiteLabel/Services/Logger/ConsoleLogManager.cs, Softeq.XToolkit.WhiteLabel/Services/Logger/ConsoleLogger.cs
- improve output format for `ConsoleLogger`
- add the ability to override JSON serializer settings
- add comments for doc
None
None
None
Not applicable
=> Refactor ConsoleLogger & JsonSerializer

Softeq.XToolkit.Common.iOS/Helpers/AttributedStringHelper.cs
- fixes #
None
- iOS
- Android
None
Not applicable
=> Custom range added to some methods of AttributedStringHelper

samples/Playground/Playground.iOS/Resources/LaunchScreen.storyboard, samples/Playground/Playground.iOS/ViewControllers/EmptyPageStoryboard.storyboard, samples/Playground/Playground.iOS/ViewControllers/MainPageStoryboard.storyboard, samples/Playground/Playground.iOS/Views/MainPageGroupHeaderViewCell.xib
Playground samples.
None
None
- iOS
None
=> Playground: iOS 13: Add basic dark support

Softeq.XToolkit.Common/Collections/ObservableRangeCollection.cs
- fixes #
None
- iOS
- Android
None
Not applicable
=> InsertRangeSorted method signature extended like in other methods

Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainer.cs, Softeq.XToolkit.WhiteLabel/Bootstrapper/DryIoCContainerBuilder.cs
ResolveLazy() method added to the IContainer interface
=> added lazy resolve method

Softeq.XToolkit.PushNotifications.iOS/NSDataExtensions.cs
- fixes #
None
- iOS
- Android
None
Not applicable
=> Missing header added

Softeq.XToolkit.Common/Collections/ObservableKeyGroupsCollectionNew.cs
Internal collection refactoring.
None
None
Not applicable
=> Small internal refactoring of ObservableKeyGroupsCollectionNew

Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardDialogsService.cs
Replace tuples to named types.
- Better readability and understanding.
=> Replace tuples

Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardDialogsService.cs
Steps:
- show modal
- show alert in modal
- cancel modal from another task
**Expected**:
modal + alert will be closed
**Actual**:
only alert closed
None
- iOS
Closing modal when have alert.
Not applicable
=> Fixed dismissing of several modal viewControllers

samples/Playground/Playground.iOS/Playground.iOS.csproj, samples/Playground/Playground.iOS/ViewControllers/Components/GesturesPageStoryboard.storyboard, samples/Playground/Playground.iOS/ViewControllers/Components/GesturesPageViewController.cs, samples/Playground/Playground.iOS/ViewControllers/Components/GesturesPageViewController.designer.cs, samples/Playground/Playground/ViewModels/Components/GesturesPageViewModel.cs, samples/Playground/Playground/ViewModels/MainPageViewModel.cs
- fixes #
None
- iOS
- Android
None
Not applicable
=> Gestures sample

Softeq.XToolkit.WhiteLabel.iOS/Controls/CustomViewBase.cs
- fixes #
None
- iOS
- Android
None
Not applicable
=> make nibName virtual

Softeq.XToolkit.Remote.Tests/Softeq.XToolkit.Remote.Tests.csproj, Softeq.XToolkit.Remote/Softeq.XToolkit.Remote.csproj, Softeq.XToolkit.Whitelabel.Tests/Softeq.XToolkit.Whitelabel.Tests.csproj, azure-pipelines/Playground.yml, azure-pipelines/nuget-Softeq.XToolkit.Remote.yml, azure-pipelines/templates/app-jobs.yml, azure-pipelines/templates/nuget-symbols-steps.yml, nuget/Softeq.XToolkit.Remote.nuspec, nuget/Softeq.XToolkit.Remote.sln, samples/Playground/Playground.sln, samples/RemoteApp/NetworkApp/NetworkApp.csproj, samples/RemoteApp/RemoteServices/RemoteServices.csproj
- Cleanup *.csproj files of Remote library;
- Added .nuspec for Remote library;
- Added DevOps pipeline for Remote library;
- Added DevOps pipeline for creating symbol NuGet packages;
- Changed Playground DevOps pipeline (added Remote lib, added all tests).
=> Improves for remote library

Softeq.XToolkit.WhiteLabel.iOS/Navigation/StoryboardFrameNavigationService.cs, Softeq.XToolkit.WhiteLabel.iOS/Navigation/StoryboardNavigation.cs
- fixes #
None
- iOS
- Android
None
Not applicable
=> fix navigation keyboard issues

Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainerBuilder.cs, Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerBuilder.cs
container improvements
Causes:
https://bitbucket.org/dadhi/dryioc/wiki/Decorators
=> IContainer improvements

README.md
- New icons for NuGet badges.
- Add Remote library badge.
None
None
=> Replace NuGet badges.

Softeq.XToolkit.WhiteLabel.Forms/Controls/FormsModalPage.cs, Softeq.XToolkit.WhiteLabel.Forms/FormsBootstrapper.cs, Softeq.XToolkit.WhiteLabel.Forms/Navigation/FormsDialogsService.cs, samples/Playground.Forms/Playground.Forms/Bootstrapper.cs, samples/Playground.Forms/Playground.Forms/ViewModels/Dialogs/DialogsRootViewModel.cs, samples/Playground.Forms/Playground.Forms/ViewModels/Dialogs/Modal/ModalPageViewModel.cs, samples/Playground.Forms/Playground.Forms/ViewModels/Dialogs/Modal/SecondModalPageViewModel.cs, samples/Playground.Forms/Playground.Forms/ViewModels/MainPageViewModel.cs, samples/Playground.Forms/Playground.Forms/Views/Dialogs/DialogsRoot.xaml, samples/Playground.Forms/Playground.Forms/Views/Dialogs/DialogsRoot.xaml.cs, samples/Playground.Forms/Playground.Forms/Views/Dialogs/Modal/ModalPage.xaml, samples/Playground.Forms/Playground.Forms/Views/Dialogs/Modal/ModalPage.xaml.cs, samples/Playground.Forms/Playground.Forms/Views/Dialogs/Modal/SecondModalPage.xaml, samples/Playground.Forms/Playground.Forms/Views/Dialogs/Modal/SecondModalPage.xaml.cs, samples/Playground.Forms/Playground.Forms/Views/MainPage.xaml, samples/Playground/Playground.sln.DotSettings
part of dialog service for Xamarin.Forms
=> Show ViewModel in modal screen

Softeq.XToolkit.WhiteLabel.Forms/FormsApp.cs, Softeq.XToolkit.WhiteLabel.Forms/Navigation/FormsViewLocator.cs, Softeq.XToolkit.WhiteLabel/Navigation/IMasterDetailViewModel.cs, samples/Playground.Forms/Playground.Forms/App.xaml.cs, samples/Playground.Forms/Playground.Forms/Bootstrapper.cs, samples/Playground.Forms/Playground.Forms/ViewModels/MasterDetailNavigation/RootMasterViewModel.cs
Xamarin forms startup improvements
=> startup improvements

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Improves for GitHub templates. To make creating and review issues and PRs more easy and clear.
None
None
None
=> Update GitHub templates

Softeq.XToolkit.WhiteLabel.Forms/Navigation/FormsFrameNavigationService.cs, Softeq.XToolkit.WhiteLabel.Forms/Navigation/FormsNavigationService.cs, Softeq.XToolkit.WhiteLabel/Navigation/FluentNavigators/FrameFluentNavigator.cs, Softeq.XToolkit.WhiteLabel/Navigation/IPlatformNavigationService.cs
- fixes #
None
- iOS
- Android
None
Not applicable
=> improve navigationservice

Softeq.XToolkit.Common.Tests/Commands/CommandsDataProvider.cs, Softeq.XToolkit.Common.Tests/Commands/RelayCommandGenericTests.cs, Softeq.XToolkit.Common/Commands/AsyncCommand.cs, Softeq.XToolkit.Common/Commands/RelayCommand.cs, Softeq.XToolkit.Common/Commands/RelayCommandGeneric.cs, Softeq.XToolkit.Common/Extensions/DictionaryExtensions.cs, Softeq.XToolkit.Common/Extensions/EnumerableExtensions.cs, Softeq.XToolkit.Common/Extensions/InternalSettingsExtensions.cs, Softeq.XToolkit.Common/Interfaces/IJsonSerializer.cs, Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DroidFragmentDialogService.cs, Softeq.XToolkit.WhiteLabel.Droid/Navigation/BundleService.cs, Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardDialogsService.cs, Softeq.XToolkit.WhiteLabel/Services/JsonSerializer.cs, Softeq.XToolkit.Whitelabel.Tests/Softeq.XToolkit.Whitelabel.Tests.csproj, Softeq.XToolkit.Whitelabel.Tests/ViewModelStub.cs
- Improve support nullability analyzer
- Disable nullability check for WL tests
- Added basic tests for RelayCommand Generic
- Some internal changes
- Improve xml-comments
None
Not applicable
=> Resolves warnings about nullability

documentation/Softeq.XToolkit.Documentation.csproj
Update package for generates API documentation.
The previous version currently not working.
=> Update DocFX package

Softeq.XToolkit.Connectivity.iOS/IosConnectivityService.cs
Add ReaderWriterLockSlim to avoid crashes when enumerating _connectionStatuses dictionary
- should fix exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
(see https://appcenter.ms/orgs/nikolai-dzneladze-hockeyapp-gw20/apps/Lansmont.iOS/crashes/errors/2955667603u/overview)
None
- iOS
None
Not applicable
=> IosConnectivityService: Add ReaderWriterLockSlim to avoid crashes

Softeq.XToolkit.WhiteLabel.iOS/Dialogs/AlertViewControllerBase.cs
Added method to create `UIAlertController` object after that you can customize alerts properties: (background, colors, etc).
Added:
- protected UIAlertController AlertViewControllerBase.CreateAlertController()
- iOS
=> Export build method to customize iOS Dialogs

documentation/articles/practices/unit-tests.md
- Update part about naming
- Add basic structure part
None
=> Update Unit Tests page

samples/Playground/Playground.iOS/ViewControllers/Collections/GroupedListPageViewController.designer.cs, samples/Playground/Playground.iOS/Views/Collections/GroupedFooterView.cs, samples/Playground/Playground.iOS/Views/Table/GroupedTableFooterView.cs, samples/Playground/Playground.iOS/Views/Table/GroupedTableHeaderView.designer.cs, samples/Playground/Playground.iOS/Views/Table/GroupedTableHeaderView.xib
See the commit messages above.
None
- iOS
=> Playground fixes

Softeq.XToolkit.Common.Tests/CommonTestClass.cs, Softeq.XToolkit.Common.Tests/Extensions/EnumExtensionsTests/EnumExtensionsTests.cs, Softeq.XToolkit.Common.Tests/Extensions/EnumExtensionsTests/TestEnum.cs, Softeq.XToolkit.Common.Tests/Extensions/EnumExtensionsTests/TestFlagsEnum.cs, Softeq.XToolkit.Common.Tests/WeakTests/WeakReferenceExTest.cs, Softeq.XToolkit.Common/Extensions/EnumExtensions.cs
- Added unit tests for EnumExtensions methods
- Added missing documentation in EnumExtensions
- Updated some of the methods in EnumExtensions to handle errors
Changed:
- TEnum SetFlag<TEnum>(this Enum value, TEnum flags) where TEnum : Enum 
=> TEnum SetFlag<TEnum>(this TEnum value, TEnum flags) where TEnum : Enum
- void Apply<TEnum>(this Action<TEnum> action) now throws ArgumentNullException when action is null instead of swallowing it
- TEnum FindByValue<TEnum>(this byte value) throws ArgumentException if value is not defined in the enum instead of returning an object without defined value
None
Not applicable
=> Add unit tests for EnumExtensions and update some of its methods

Softeq.XToolkit.WhiteLabel.iOS/AppDelegateBase.cs, samples/Playground/Playground.Droid/CustomDroidBootstrapper.cs, samples/Playground/Playground.iOS/CustomIosBootstrapper.cs, samples/Playground/Playground.iOS/ViewControllers/Collections/CompositionalLayoutPageViewController.cs, samples/Playground/Playground.iOS/ViewControllers/Components/GesturesPageStoryboard.storyboard, samples/Playground/Playground.iOS/ViewControllers/Components/GesturesPageViewController.cs, samples/Playground/Playground.iOS/ViewControllers/Pages/DetailsPageStoryboard.storyboard, samples/Playground/Playground.iOS/ViewControllers/StartPageViewController.cs, samples/Playground/Playground/ViewModels/MainPageViewModel.cs
- Improve Playground features support for iOS 12, 13 and Android
- Fix iOS 12 crash
None
- iOS
=> Improve compatibility

nuget/Softeq.XToolkit.Bindings.nuspec, nuget/Softeq.XToolkit.Common.nuspec, nuget/Softeq.XToolkit.Permissions.nuspec, nuget/Softeq.XToolkit.PushNotifications.nuspec, nuget/Softeq.XToolkit.WhiteLabel.Essentials.nuspec, nuget/Softeq.XToolkit.WhiteLabel.Forms.nuspec, nuget/Softeq.XToolkit.WhiteLabel.nuspec
Changes: https://github.com/Softeq/XToolkit.WhiteLabel/compare/v2.0.0-beta6...0ff12a393c5818b36b6b79fc328485a4b4288851
=> New beta version 7

Softeq.XToolkit.Common.Tests/Files/BaseFileProviderTests/BaseFileProviderTests.cs, Softeq.XToolkit.Common.Tests/Files/BaseFileProviderTests/MockFileSystemWrapper.cs, Softeq.XToolkit.Common/Files/Abstractions/IDirectory.cs, Softeq.XToolkit.Common/Files/Abstractions/IFile.cs, Softeq.XToolkit.Common/Files/Abstractions/IFileSystem.cs, Softeq.XToolkit.Common/Files/BaseFileProvider.cs, Softeq.XToolkit.Common/Files/InternalStorageFileProvider.cs, Softeq.XToolkit.Common/Softeq.XToolkit.Common.csproj
To #337 
- Exported only used System.IO abstractions
- Remove System.IO.Abstractions package from Common
- Update tests
=> Rework file provider tests

Softeq.XToolkit.Common.Droid.Tests/Softeq.XToolkit.Common.Droid.Tests.csproj, Softeq.XToolkit.Common.Droid.Tests/TextFilters/ForbiddenCharsInputFilterTests.cs
Tests for ForbiddenCharsInputFilter added
None
- Android
None
Not applicable
=> Tests for ForbiddenCharsInputFilter

Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DialogFragmentBase.cs, samples/Playground/Playground.Droid/Playground.Droid.csproj, samples/Playground/Playground.Droid/Resources/anim/slide_down_dialog.xml, samples/Playground/Playground.Droid/Resources/anim/slide_up_dialog.xml, samples/Playground/Playground.Droid/Resources/values/styles.xml, samples/Playground/Playground.Droid/Views/Dialogs/SimpleDialogPageFragment.cs
Added a property to DialogFragmentBase that allows to set up custom window animations for the dialog
None
- Android
None
Not applicable
=> Android: add property to set up custom animation for dialogs

Softeq.XToolkit.Common.Droid.Tests/MainActivity.cs, Softeq.XToolkit.Common.Droid.Tests/Properties/AndroidManifest.xml, Softeq.XToolkit.Common.Droid.Tests/TextFilters/ForbiddenCharsInputFilterTests.cs, samples/Playground/Playground.Droid/Resources/layout/activity_dialogs.xml, samples/Playground/Playground.Droid/Views/MainPageActivity.cs
- Add ScrollView to Playground.Droid Dialogs
- Expand all groupd on Main Page Playground.Droid
- Raise Android SDK for Common.Droid.Tests
None
- Android
=> Improve/playground & droid tests

Softeq.XToolkit.WhiteLabel.Tests/Location/LocationModelTests/LocationModelTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Validation/Rules/EmailRuleTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Validation/Rules/IsValueTrueRuleTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Validation/Rules/StringLengthRuleTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Validation/Rules/StringNotEmptyRuleTests.cs, Softeq.XToolkit.WhiteLabel/Location/LocationModel.cs, Softeq.XToolkit.WhiteLabel/Validation/IValidationRule.cs, Softeq.XToolkit.WhiteLabel/Validation/Rules/EmailRule.cs, Softeq.XToolkit.WhiteLabel/Validation/Rules/IsValueTrueRule.cs, Softeq.XToolkit.WhiteLabel/Validation/Rules/StringLengthRule.cs, Softeq.XToolkit.WhiteLabel/Validation/Rules/StringNotEmptyRule.cs, Softeq.XToolkit.Whitelabel.Tests/Softeq.XToolkit.Whitelabel.Tests.csproj
- Validation rules tests reworked a little bit
- Documentation for validation rules added where needed
None
None
Not applicable
=> Validation rules tests

Softeq.XToolkit.WhiteLabel.Tests/Navigation/DialogResultTests/DialogResultDataProvider.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/DialogResultTests/DialogResultTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/NavigationParameterModelTests/NavigationParameterModelDataProvider.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/NavigationParameterModelTests/NavigationParameterModelTests.cs, Softeq.XToolkit.WhiteLabel/Navigation/DialogResult.cs, Softeq.XToolkit.WhiteLabel/Navigation/NavigationParameterModel.cs
Documentation and tests added for NavigationParameterModel and DialogResult
None
None
Not applicable
=> Documentation and tests for NavigationParameterModel and DialogResult

Softeq.XToolkit.WhiteLabel.Tests/Mvvm/CommandActionTests/CommandActionTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Mvvm/CommandActionTests/CommandActionTestsDataProvider.cs, Softeq.XToolkit.WhiteLabel/Mvvm/CommandAction.cs
Tests and documentation for CommandAction added
None
None
Not applicable
=> Tests and documentation for CommandAction

Softeq.XToolkit.WhiteLabel.Tests/Mvvm/DialogViewModelComponentTests/DialogViewModelComponentTests.cs, Softeq.XToolkit.WhiteLabel/Mvvm/DialogViewModelBase.cs, Softeq.XToolkit.WhiteLabel/Mvvm/DialogViewModelComponent.cs
Tests and documentation for DialogViewModelComponent added
None
None
Not applicable
=> Tests and documentation for DialogViewModelComponent

Softeq.XToolkit.WhiteLabel.Tests/Mvvm/ViewModelBaseTests/ViewModelBaseTests.cs, Softeq.XToolkit.WhiteLabel/Mvvm/IViewModelBase.cs, Softeq.XToolkit.WhiteLabel/Mvvm/ViewModelBase.cs
Documentation and tests for ViewModelBase added
None
None
Not applicable
=> Documentation and tests for ViewModelBase

Softeq.XToolkit.WhiteLabel.Tests/Model/TabItemTests/TabItemTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Mvvm/RootFrameNavigationPageViewModelTests/RootFrameNavigationPageViewModelTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Mvvm/RootFrameNavigationViewModelBaseTests/RootFrameNavigationViewModelBaseTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Mvvm/ViewModelBaseTests/ViewModelBaseTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Mvvm/ViewModelFactoryTests/ViewModelFactoryTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/DialogResultTests/DialogResultTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/DialogResultTests/DialogResultTestsDataProvider.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/FluentNavigators/DialogFluentNavigatorTests/DialogFluentNavigatorTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/FluentNavigators/FluentNavigatorExtensionsTests/FluentNavigatorExtensionsTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/FluentNavigators/FluentNavigatorExtensionsTests/FluentNavigatorExtensionsTestsDataProvider.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/FluentNavigators/FluentNavigatorTestsDataProvider.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/FluentNavigators/FrameFluentNavigatorTests/FrameFluentNavigatorTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/FluentNavigators/PageFluentNavigatorTests/PageFluentNavigatorTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/PageNavigationServiceTests/PageNavigationServiceTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Stubs/DialogViewModelStub.cs, Softeq.XToolkit.WhiteLabel.Tests/Stubs/RootFrameNavigationViewModelBaseStub.cs, Softeq.XToolkit.WhiteLabel.Tests/Stubs/ViewModelStub.cs, Softeq.XToolkit.WhiteLabel/Mvvm/RootFrameNavigationPageViewModel.cs, Softeq.XToolkit.WhiteLabel/Mvvm/RootFrameNavigationViewModelBase.cs, Softeq.XToolkit.WhiteLabel/Navigation/FluentNavigators/DialogFluentNavigator.cs, Softeq.XToolkit.WhiteLabel/Navigation/FluentNavigators/FluentNavigatorBase.cs, Softeq.XToolkit.WhiteLabel/Navigation/FluentNavigators/FluentNavigatorExtensions.cs, Softeq.XToolkit.WhiteLabel/Navigation/FluentNavigators/FrameFluentNavigator.cs, Softeq.XToolkit.WhiteLabel/Navigation/FluentNavigators/PageFluentNavigator.cs, Softeq.XToolkit.WhiteLabel/Navigation/FrameNavigationServiceExtensions.cs, Softeq.XToolkit.WhiteLabel/Navigation/IFrameNavigationService.cs
- Tests and Documentation added for FluentNavigators and RootFrameNavigationPageViewModels
None
None
Not applicable
=> Tests and Documentation for FluentNavigators and RootFrameNavigationPageViewModels

Softeq.XToolkit.WhiteLabel.Tests/Navigation/DialogsServiceExtensionsTests/DialogsServiceExtensionsTests.cs, Softeq.XToolkit.WhiteLabel.Tests/Navigation/FrameNavigationServiceExtensionsTests/FrameNavigationServiceExtensionsTests.cs, Softeq.XToolkit.WhiteLabel/Navigation/DialogsServiceExtensions.cs, Softeq.XToolkit.WhiteLabel/Navigation/FrameNavigationServiceExtensions.cs
Tests and documentation for DialogsServiceExtensions and FrameNavigationServiceExtensions added
None
None
Not applicable
=> Tests and documentation for DialogsServiceExtensions and FrameNavigationServiceExtensions

Softeq.XToolkit.WhiteLabel.Forms/Navigation/FormsNavigationService.cs, Softeq.XToolkit.WhiteLabel.Forms/Softeq.XToolkit.WhiteLabel.Forms.csproj, nuget/Softeq.XToolkit.WhiteLabel.Forms.nuspec, samples/Playground.Forms/Playground.Forms.Droid/Playground.Forms.Droid.csproj, samples/Playground.Forms/Playground.Forms.iOS/Playground.Forms.iOS.csproj, samples/Playground.Forms/Playground.Forms/Playground.Forms.csproj, samples/Playground.Forms/Playground.Forms/Views/Components/AsyncCommandsPage.xaml, samples/Playground.Forms/Playground.Forms/Views/Components/PaginationSearchPage.xaml, samples/Playground.Forms/Playground.Forms/Views/Components/PermissionsPage.xaml, samples/Playground.Forms/Playground.Forms/Views/Components/ValidationPage.xaml, samples/Playground.Forms/Playground.Forms/Views/Dialogs/DialogsRootPage.xaml, samples/Playground.Forms/Playground.Forms/Views/Dialogs/Modal/ModalPage.xaml, samples/Playground.Forms/Playground.Forms/Views/Dialogs/Modal/SecondModalPage.xaml, samples/Playground.Forms/Playground.Forms/Views/MainPage.xaml, samples/Playground.Forms/Playground.Forms/Views/MasterDetailNavigation/DetailPage.xaml, samples/Playground.Forms/Playground.Forms/Views/MasterDetailNavigation/DrillNavigation/DrillLevel1Page.xaml, samples/Playground.Forms/Playground.Forms/Views/MasterDetailNavigation/DrillNavigation/DrillLevel2Page.xaml, samples/Playground.Forms/Playground.Forms/Views/MasterDetailNavigation/MasterPage.xaml, samples/Playground.Forms/Playground.Forms/Views/MasterDetailNavigation/RootMasterDetailPage.xaml, samples/Playground.Forms/Playground.Forms/Views/MasterDetailNavigation/SelectedItemPage.xaml, samples/Playground.Forms/Playground.Forms/Views/SimpleNavigation/FirstPage.xaml, samples/Playground.Forms/Playground.Forms/Views/SimpleNavigation/SecondPage.xaml
- Update version of XF packages
- Update Playground.Forms to support Dark/Light themes
- Fix Forms navigation internal exception
None
None
=> Update XF to 4.8.0.1560

Softeq.XToolkit.PushNotifications.Droid/DroidPushNotificationParser.cs, Softeq.XToolkit.PushNotifications.Droid/DroidPushNotificationsService.cs, Softeq.XToolkit.PushNotifications/ForegroundNotificationOptions.cs, Softeq.XToolkit.PushNotifications/IPushNotificationParser.cs, Softeq.XToolkit.PushNotifications/IPushNotificationsHandler.cs, Softeq.XToolkit.PushNotifications/IPushNotificationsReceiver.cs, Softeq.XToolkit.PushNotifications/IPushNotificationsService.cs, Softeq.XToolkit.PushNotifications/IPushTokenStorageService.cs, Softeq.XToolkit.PushNotifications/IRemotePushNotificationsService.cs, Softeq.XToolkit.PushNotifications/PushNotificationModel.cs, Softeq.XToolkit.PushNotifications/PushNotificationRegistrationResult.cs, Softeq.XToolkit.PushNotifications/PushNotificationsServiceBase.cs, Softeq.XToolkit.PushNotifications/PushNotificationsUnregisterOptions.cs, Softeq.XToolkit.PushNotifications/PushTokenStorageService.cs
- DroidPushNotificationParser improved to handle localized notifications
- Documentation fixes
None
- Android
None
Not applicable
=> PushNotifications library improvement

Softeq.XToolkit.PushNotifications.Droid/INotificationsSettingsProvider.cs, Softeq.XToolkit.PushNotifications.Droid/NotificationIntentActivityInfo.cs, Softeq.XToolkit.PushNotifications.Droid/NotificationsHelper.cs
- LaunchedFromPushNotificationKey added to INotificationsSettingsParser;
- Documentation fixes
None
- Android
None
Not applicable
=> Droid notification handling improvement

azure-pipelines/Documentation.yml, documentation/Softeq.XToolkit.Documentation.csproj
=> Update documentation pipeline

Softeq.XToolkit.Permissions.Droid/Softeq.XToolkit.Permissions.Droid.csproj, Softeq.XToolkit.Permissions/Softeq.XToolkit.Permissions.csproj, Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj, Softeq.XToolkit.WhiteLabel/Softeq.XToolkit.WhiteLabel.csproj
Xamarin.Essentials nuget updated
=> Xamarin.Essentials nuget updated

.gitignore, Softeq.XToolkit.Bindings.Tests/Softeq.XToolkit.Bindings.Tests.csproj, Softeq.XToolkit.Common.Tests/Softeq.XToolkit.Common.Tests.csproj, Softeq.XToolkit.Remote.Tests/Softeq.XToolkit.Remote.Tests.csproj, Softeq.XToolkit.WhiteLabel.Tests/Softeq.XToolkit.WhiteLabel.Tests.csproj, Tests.Shared.props, azure-pipelines/templates/app-jobs.yml, generate_test_coverage_report.sh
Script to generate coverage report on the local machine.
Thanks @KirylAkulich1 
None
None
Not applicable
=> Add script to generate coverage report

Softeq.XToolkit.Common.Tests/Softeq.XToolkit.Common.Tests.csproj, Softeq.XToolkit.WhiteLabel.Forms/Softeq.XToolkit.WhiteLabel.Forms.csproj, Tests.Shared.props, documentation/Softeq.XToolkit.Documentation.csproj, samples/Playground.Forms/Playground.Forms.Droid/Playground.Forms.Droid.csproj, samples/Playground.Forms/Playground.Forms.iOS/Playground.Forms.iOS.csproj, samples/Playground.Forms/Playground.Forms/Playground.Forms.csproj
Update packages for:
- Xamarin.Forms
- Unit tests
- Documentation
None
None
None
Not applicable
=> Update packages for tests and XForms

NuGet.targets, Softeq.XToolkit.Common.Droid/Softeq.XToolkit.Common.Droid.csproj, Softeq.XToolkit.Common.iOS/Softeq.XToolkit.Common.iOS.csproj, Softeq.XToolkit.Common/Softeq.XToolkit.Common.csproj, nuget/Softeq.XToolkit.Common.nuspec
- SourceLink: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink
- Update XToolkit.Common Nuget version
None
None
Not applicable
=> Add SourceLink for XToolkit.Common

Softeq.XToolkit.Bindings.Droid/Softeq.XToolkit.Bindings.Droid.csproj, Softeq.XToolkit.Bindings.iOS/Softeq.XToolkit.Bindings.iOS.csproj, Softeq.XToolkit.Bindings/Softeq.XToolkit.Bindings.csproj, Softeq.XToolkit.Permissions.Droid/Softeq.XToolkit.Permissions.Droid.csproj, Softeq.XToolkit.Permissions.iOS/Softeq.XToolkit.Permissions.iOS.csproj, Softeq.XToolkit.Permissions/Softeq.XToolkit.Permissions.csproj, Softeq.XToolkit.PushNotifications.Droid/Softeq.XToolkit.PushNotifications.Droid.csproj, Softeq.XToolkit.PushNotifications.iOS/Softeq.XToolkit.PushNotifications.iOS.csproj, Softeq.XToolkit.PushNotifications/Softeq.XToolkit.PushNotifications.csproj, Softeq.XToolkit.Remote/Softeq.XToolkit.Remote.csproj, Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj, Softeq.XToolkit.WhiteLabel.Essentials.Droid/Softeq.XToolkit.WhiteLabel.Essentials.Droid.csproj, Softeq.XToolkit.WhiteLabel.Essentials.iOS/Softeq.XToolkit.WhiteLabel.Essentials.iOS.csproj, Softeq.XToolkit.WhiteLabel.Essentials/Softeq.XToolkit.WhiteLabel.Essentials.csproj, Softeq.XToolkit.WhiteLabel.Forms/Softeq.XToolkit.WhiteLabel.Forms.csproj, Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj, Softeq.XToolkit.WhiteLabel/Softeq.XToolkit.WhiteLabel.csproj, documentation/articles/contributing-documentation.md, documentation/articles/nuget-release-process.md, documentation/articles/toc.yml, documentation/build.sh, nuget/Softeq.XToolkit.Bindings.nuspec, nuget/Softeq.XToolkit.Common.nuspec, nuget/Softeq.XToolkit.Permissions.nuspec, nuget/Softeq.XToolkit.PushNotifications.nuspec, nuget/Softeq.XToolkit.Remote.nuspec, nuget/Softeq.XToolkit.WhiteLabel.Essentials.nuspec, nuget/Softeq.XToolkit.WhiteLabel.Forms.nuspec, nuget/Softeq.XToolkit.WhiteLabel.nuspec, tools/set-headers.sh
=> New beta version 8

azure-pipelines/templates/vars.yml
Update:
- Xamarin
- XCode
Based on: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
=> Update CI vars.yml

azure-pipelines/Documentation.yml, azure-pipelines/XToolkit.yml, documentation/Softeq.XToolkit.Documentation.csproj, documentation/build.sh, documentation/nested-namespaces.ps1, documentation/toc.yml, documentation/unflatten-namespaces.ps1
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="268" alt="Screen Shot 2022-01-20 at 12 04 57 AM" src="https://user-images.githubusercontent.com/766193/150213583-1ea0d93c-e75f-43ff-9d49-fd2e6f47f94d.png">
<td><img width="250" alt="Screen Shot 2022-01-20 at 12 05 19 AM" src="https://user-images.githubusercontent.com/766193/150213623-eaa6b88f-c424-46c9-b473-7e5d73e8ac8a.png">
</table>
=> Documentation API with nested namespaces

Softeq.XToolkit.Bindings/Extensions/BindableExtensions.cs, Softeq.XToolkit.Common/Collections/BiDictionary.cs, Softeq.XToolkit.Common/Disposables/Disposable.cs, Softeq.XToolkit.Common/Extensions/EnumExtensions.cs, Softeq.XToolkit.Common/Extensions/StringExtensions.cs, Softeq.XToolkit.Common/Files/Abstractions/IDirectory.cs, Softeq.XToolkit.Common/Files/Abstractions/IFile.cs, Softeq.XToolkit.Common/Files/Abstractions/IFileSystem.cs, Softeq.XToolkit.Common/Files/BaseFileProvider.cs, Softeq.XToolkit.Common/Files/InternalStorageFileProvider.cs, Softeq.XToolkit.Common/Files/ResourceFileProvider.cs, Softeq.XToolkit.Common/GenericEventArgs.cs, Softeq.XToolkit.Common/Helpers/TagsHelper.cs, Softeq.XToolkit.Common/Logger/ConsoleLogManager.cs, Softeq.XToolkit.Common/Logger/ConsoleLogger.cs, Softeq.XToolkit.Common/Logger/ILogManager.cs, Softeq.XToolkit.Common/Threading/Execute.cs, Softeq.XToolkit.WhiteLabel.iOS/Interfaces/IViewControllerProvider.cs, Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerBuilder.cs, documentation/articles/xtoolkit/common.md
Add some additional API docs.
None
None
=> Improve docs

Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj, Softeq.XToolkit.WhiteLabel.Droid/ViewComponents/BottomNavigationComponentBase.cs, samples/Playground.Forms/Playground.Forms.Droid/DroidBootstrapper.cs, samples/Playground.Forms/Playground.Forms.Droid/Playground.Forms.Droid.csproj
Android Material Design updated to 1.4
None
- Android
None
Not applicable
=> Update MaterialDesign to 1.4

Softeq.XToolkit.Permissions.Droid/Softeq.XToolkit.Permissions.Droid.csproj, Softeq.XToolkit.Permissions.iOS/Softeq.XToolkit.Permissions.iOS.csproj, Softeq.XToolkit.Permissions/Softeq.XToolkit.Permissions.csproj, Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj, Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj, Softeq.XToolkit.WhiteLabel/Softeq.XToolkit.WhiteLabel.csproj
Update xamarin essentials
- fixes #
None
- iOS
- Android
None
Not applicable
=> xamarin essentials updated

nuget/Softeq.XToolkit.Bindings.nuspec, nuget/Softeq.XToolkit.Common.nuspec, nuget/Softeq.XToolkit.Permissions.nuspec, nuget/Softeq.XToolkit.PushNotifications.nuspec, nuget/Softeq.XToolkit.Remote.nuspec, nuget/Softeq.XToolkit.WhiteLabel.Essentials.nuspec, nuget/Softeq.XToolkit.WhiteLabel.Forms.nuspec, nuget/Softeq.XToolkit.WhiteLabel.nuspec
Changes: https://github.com/Softeq/XToolkit.WhiteLabel/compare/v2.0.0-beta8...release/beta10
Milestone: https://github.com/Softeq/XToolkit.WhiteLabel/milestone/9?closed=1
=> New beta version 10

Softeq.XToolkit.Common.Tests/Files/BaseFileProviderTests/BaseFileProviderTests.cs, Softeq.XToolkit.Common.Tests/Softeq.XToolkit.Common.Tests.csproj, _CodeStyles.targets, _Tests.Platform.targets, _Tests.targets, azure-pipelines/templates/vars.yml, documentation/Softeq.XToolkit.Documentation.csproj, documentation/build.sh, documentation/nested-namespaces.ps1
Update NuGet packages for:
- Unit testing
- Source code analyzing
- CI builds
None
None
Not applicable
=> Update infrastructure packages

Softeq.XToolkit.PushNotifications.Droid/Softeq.XToolkit.PushNotifications.Droid.csproj
Update package for android 12 support
- [ x] I have read the [CONTRIBUTING](https://github.com/Softeq/XToolkit.WhiteLabel/blob/master/.github/CONTRIBUTING.md) document
- [x ] My code follows the [code styles](https://github.com/Softeq/dotnet-guidelines)
- [x ] Targets the correct branch
x
=> nuget updated

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, .github/labeler.yml, .github/workflows/labeler.yml, documentation/articles/developer-guide.md, tools/binobj-cleaner.sh
Some small improvements more details in commit titles.
None
None
Not applicable
=> Repository improvements

Softeq.XToolkit.WhiteLabel.Droid/Navigation/DroidFrameNavigationService.cs
Given fix provided for situations while navigation operation can be triggered simultaneously.
For example in Halo project crash happens when user closed dialog activity and right after that navigating to another view. It happens because in MainActivity’s OnResume method we call RestoreNavigation, and sometimes RestoreNavigation calls for properties that has been changed by navigation in another thread.
See piece of logs:
> 2022-11-08 19:03:17.558 6200-12784/? V/mono-stdout: LoggingDialogsServiceDecorator: Dialog closed: FlowContainerViewModel
> 2022-11-08 19:03:17.607 6200-6200/? V/mono-stdout: MainActivity: OnResume
> 2022-11-08 19:03:17.614 6200-12378/? V/mono-stdout: HaloDroidFrameNavigationService: Navigated To: OnboardingAlmostReadyViewModel
> 2022-11-08 19:03:17.673 6200-6200/? …
=> Implemented thread safe navigation for Android

Softeq.XToolkit.PushNotifications.Droid/Services/DroidPushNotificationsConsumer.cs, Softeq.XToolkit.PushNotifications.iOS/Services/IosPushNotificationsConsumer.cs, Softeq.XToolkit.PushNotifications/Abstract/IPushNotificationsHandler.cs, Softeq.XToolkit.PushNotifications/Abstract/IPushTokenStorageService.cs, Softeq.XToolkit.PushNotifications/Abstract/IPushTokenSynchronizer.cs, Softeq.XToolkit.PushNotifications/Abstract/IRemotePushNotificationsService.cs, Softeq.XToolkit.PushNotifications/PushTokenStorageService.cs, Softeq.XToolkit.PushNotifications/PushTokenSynchronizer.cs
- fixes #
None
- iOS
- Android
None
Not applicable
=> add token synchronizer

Softeq.XToolkit.Common/Commands/AsyncCommandBase.cs, Softeq.XToolkit.Common/Files/BaseFileProvider.cs, Softeq.XToolkit.Common/Threading/TaskDeferral.cs, Softeq.XToolkit.Common/Timers/Timer.cs, Softeq.XToolkit.Permissions/PermissionsService.cs, Softeq.XToolkit.WhiteLabel.Tests/GlobalSuppressions.cs, XToolkit.ruleset, samples/Playground/Playground.Droid/GlobalSuppressions.cs, samples/Playground/Playground.iOS/GlobalSuppressions.cs, samples/Playground/Playground/GlobalSuppressions.cs
Rule [CA2007](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007?view=vs-2019)
None
None
None
Not applicable
=> Show warning when ConfigureAwait should be used

azure-pipelines/templates/vars.yml
Update CI build environment.
None
None
Not applicable
=> Update CI environment

Softeq.XToolkit.Common.Tests/Collections/ObservableKeyGroupsCollectionTest/ObservableKeyGroupsCollectionTestsCountChanged.cs, Softeq.XToolkit.Common/Collections/ObservableKeyGroupsCollection.cs
- fixes #474
None
None
Not applicable
=> Add binding support for Count property (ObservableKeyGroupsCollection)
