Softeq.XToolkit.Common.iOS/Extensions/UIViewExtensions.cs
Softeq.XToolkit.Common/EventArguments/GenericEventArgs.cs

instead of using every time 
`var e = new GenericEventArgs<MyFavoriteCustomClass>(MyFavoriteCustomClass.CustomPropertyName)`
For now we can use 
`var e = GenericEventArgs.From(MyFavoriteCustomClass.CustomPropertyName)`

improved generic event args

---

Softeq.XToolkit.Common.iOS/Helpers/AttributedStringHelper.cs

- Add `encoding` args for `BuildAttributedStringFromHtml`, by default UTF8
- Add `ParagraphStyle`

[iOS] Improves for AttributedString

---

Softeq.XToolkit.Common.Droid/Extensions/ContextExtensions.cs
Softeq.XToolkit.Common.Droid/Extensions/EditTextExtensions.cs
Softeq.XToolkit.Common.Droid/Extensions/ViewExtensions.cs
Softeq.XToolkit.Common.Droid/Softeq.XToolkit.Common.Droid.csproj

- Remove `SetMaxLengthWithForbiddenSymbols` method, currently can use this syntax:
```cs
_editView.SetFilters(
new InputFilterLengthFilter(maxLength),
new ForbiddenCharsInputFilter(forbiddenCharacters),
...);
```
- Fixed #89 
- Export view extensions to separate file.

[Droid] Refactor extensions

---

Softeq.XToolkit.WhiteLabel/Softeq.XToolkit.WhiteLabel.csproj

Current NuGet package `DryIoc` provides via linked sources.
`DryIoc.dll` package contains compiled assembly.
> Source code is the default way of distribution (e.g. DryIoc package) for a historical reasons. If you want a "normal" assembly reference, please use the packages with .dll suffix (e.g. DryIoc.dll package). https://bitbucket.org/dadhi/dryioc/wiki/InstallationOptions.md

Change DryIoc NuGet

---

Softeq.XToolkit.Bindings/BindingExtensions.cs
Softeq.XToolkit.Bindings/Extensions/BindableExtensions.cs

- Some refactor
- Add the extension method for advanced configuration of Binding object. Fixed #172 
Example:
```cs
// UISearchBar
this.Bind(
() => ViewModel.Text,
() => SearchBar.Text,
BindingMode.TwoWay,
configure:
binding => binding.ObserveTargetEvent<UISearchBarTextChangedEventArgs>(
nameof(SearchBar.TextChanged)));
// UISegmentedControl
this.Bind(
() => ViewModel.SelectedIndex,
() => SegmentedControl.SelectedSegment,
BindingMode.TwoWay,
configure:
binding => binding.ObserveTargetEvent(
nameof(SegmentedControl.PrimaryActionTriggered)));
```

Add extension method for advanced configuration of Binding object.

---

Softeq.XToolkit.WhiteLabel.Droid/DroidBootstrapper.cs
Softeq.XToolkit.WhiteLabel.iOS/IosBootstraper.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainer.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainerBuilder.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IfRegistered.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/BootstrapperBase.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerAdapter.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerBuilder.cs

- Fixed services registration order.
- Internal refactoring.
**Important**
- When you register new instances of internal services, you need to use `IfRegistered.Replace` otherwise you will have runtime exception about duplication registration.
**Additional notes**
- **Lazy resolving** - Because we use DryIoc under the hood, our `IContainer` has the implicit ability for lazy, factory resolving ([DryIoc doc](https://bitbucket.org/dadhi/dryioc/wiki/Wrappers#markdown-header-predefined-wrappers), [Autofac doc](https://autofaccn.readthedocs.io/en/latest/resolve/relationships.html#delayed-instantiation-lazy-b))
Obsoleted:
- `IContainer.ResolveLazy<TService>` look above.
Changed:
- enum `IfRegistered.AppendNewImplementation` => `IfRegistered.AppendNew`
- iOS
- Android
None …

Refactor bootstrapper & containerBuilder

---

Softeq.XToolkit.Common.iOS/Extensions/DateTimeExtensions.cs

Fixed obsolete warning with iOS DateTime extensions.
Resources:
- [NSDate.cs sources](https://github.com/xamarin/xamarin-macios/blob/master/src/Foundation/NSDate.cs)
- [NSDate conversions after Unified.](https://forums.xamarin.com/discussion/comment/118230/#Comment_118230)
Changed:
- `NSDateToDateTime` => `DateTime ToDateTime(NSDate)`
- `DateTimeToNSDate` => `NSDate ToNsDate(DateTime)`
- `ToNSDateLocal` => `ToNsDateLocal`
- iOS
None
Not applicable

Update iOS DateTime extensions

---

Softeq.XToolkit.Bindings/BindingGeneric.cs

Fixing bug in bindings regarding using of fallback value for source property. Previously, fallback value was used without conversion to target type, which causes an InvalidCastException if source and target properties are not of the same type.
None
- iOS
- Android
None
Not applicable

Apply converter for fallback value

---

Softeq.XToolkit.Permissions.iOS/PermissionsService.cs
Softeq.XToolkit.PushNotifications.Droid/DroidPushNotificationParser.cs
Softeq.XToolkit.PushNotifications/IPushNotificationsService.cs
Softeq.XToolkit.PushNotifications/PushNotificationModel.cs
Softeq.XToolkit.PushNotifications/PushNotificationRegistrationResult.cs
Softeq.XToolkit.PushNotifications/PushNotificationsServiceBase.cs

Added an async Register for push notifications method
Added:
- `Task<PushNotificationRegistrationResult> RegisterForPushNotificationsAsync();` to `IPushNotificationsService`
- `PushNotificationRegistrationResult` class
- iOS
- Android
`CheckPermissionsAsync` for `NotificationsPermission` now returns `PermissionStatus.Unknown` if permission was not requested yet
Not applicable

Push notifications: add asynchronous method for subscribe

---

nuget/Softeq.XToolkit.Bindings.nuspec
nuget/Softeq.XToolkit.Common.nuspec
nuget/Softeq.XToolkit.Permissions.nuspec
nuget/Softeq.XToolkit.PushNotifications.nuspec
nuget/Softeq.XToolkit.Remote.nuspec
nuget/Softeq.XToolkit.WhiteLabel.nuspec

New beta release XToolkit components.
Main changes: 🚀 
- C# 8.0, Nullable enabled PR #213 
- Android.Support libraries -> 28.0.0.3
- Android TargetFramework -> v10.0
- Net Standard libraries -> netstandard2.1
- C# 7.3 -> 8.0 & Nullable
- netstandard2.0 -> netstandard2.1
- `BiDictionary` reworked PR #225
- Changed `DateTimeExtensions`, `StringExtensions` PR #236
- Changed `TagsHelper`, `TextRange` PR #234
- ConsoleLogger PR #231
- C# 7.3 -> 8.0 & Nullable
- TargetFramework v9.0 -> v10.0
- C# 7.3 -> 8.0 & Nullable
- DateTimeExtensions PR #210
- C# 7.3 -> 8.0 & Nullable
- `TextRangeTests`
- `TagsHelperTests`
- `HashHelperTests`
- `BiDictionaryTests`
- `AssemblyExtensionsTests`
- `DateTimeExtensionsTests`
- `InternalSettingsExtensionsTests`
- `ConsoleLogManagerTests`
- `ConsoleLoggerTests`
- …

New beta version 4

---

Softeq.XToolkit.WhiteLabel.Droid/DroidBootstrapper.cs
Softeq.XToolkit.WhiteLabel.Droid/Navigation/DroidViewLocator.cs
Softeq.XToolkit.WhiteLabel.Droid/Navigation/IViewLocator.cs
Softeq.XToolkit.WhiteLabel.iOS/Helpers/ViewControllerHelper.cs
Softeq.XToolkit.WhiteLabel.iOS/IosBootstraper.cs
Softeq.XToolkit.WhiteLabel.iOS/Navigation/IViewLocator.cs
Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardViewLocator.cs
Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj
Softeq.XToolkit.WhiteLabel/Bootstrapper/BootstrapperBase.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/BootstrapperWithViewModelLookup.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerAdapter.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/ViewModelFinderBase.cs

Export duplicated logic to find view models by platform-specific view types.
Added:
- class `BootstrapperWithViewModelLookup` - incapsulate logic about registering ViewModels and re-configuring ViewLocator;
- class `ViewModelFinderBase` - incapsulate logic about lookup ViewModel types from known assemblies;
- class `DroidViewModelFinder` - Android-specific finder;
- class `IosViewModelFinder` - iOS-specific finder;
- class `ViewModelToViewMap` - type alias to ViewModel to View mapping; 
- class `ViewControllerHelper` - iOS helper with methods for instantiate ViewControllers;
- class `BootstrapperBase`
- method `RegisterTypesFromAssemblies(IContainerBuilder builder, IList<Assembly> assemblies)` - for make additional search and registrations from cached assemblies.
Changed:
- class …

Refactor bootstrapper

---

Directory.Build.props
Softeq.XToolkit.Bindings.Droid/Softeq.XToolkit.Bindings.Droid.csproj
Softeq.XToolkit.Bindings.iOS/Softeq.XToolkit.Bindings.iOS.csproj
Softeq.XToolkit.Bindings/Softeq.XToolkit.Bindings.csproj
Softeq.XToolkit.Common.Droid/Softeq.XToolkit.Common.Droid.csproj
Softeq.XToolkit.Common.Tests/Softeq.XToolkit.Common.Tests.csproj
Softeq.XToolkit.Common.iOS/Softeq.XToolkit.Common.iOS.csproj
Softeq.XToolkit.Common/Softeq.XToolkit.Common.csproj
Softeq.XToolkit.Connectivity.iOS/Softeq.XToolkit.Connectivity.iOS.csproj
Softeq.XToolkit.Connectivity/Softeq.XToolkit.Connectivity.csproj
Softeq.XToolkit.Permissions.Droid/Softeq.XToolkit.Permissions.Droid.csproj
Softeq.XToolkit.Permissions.iOS/Softeq.XToolkit.Permissions.iOS.csproj
Softeq.XToolkit.Permissions/Softeq.XToolkit.Permissions.csproj
Softeq.XToolkit.PushNotifications.Droid/Softeq.XToolkit.PushNotifications.Droid.csproj
Softeq.XToolkit.PushNotifications.iOS/Softeq.XToolkit.PushNotifications.iOS.csproj
Softeq.XToolkit.PushNotifications/Softeq.XToolkit.PushNotifications.csproj
Softeq.XToolkit.Remote.Tests/Softeq.XToolkit.Remote.Tests.csproj
Softeq.XToolkit.Remote/Softeq.XToolkit.Remote.csproj
Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj
Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj
Softeq.XToolkit.WhiteLabel/Softeq.XToolkit.WhiteLabel.csproj
Softeq.XToolkit.Whitelabel.Tests/Softeq.XToolkit.Whitelabel.Tests.csproj

Added `Directory.Build.props` to share common build properties (LangVersion, Nullable) between all XToolkit projects.
- fixes #246
None
None
Not applicable

Share common build properties

---

Softeq.XToolkit.Common.Tests/Extensions/ListExtensionsTests/ListExtensionsTests.cs
Softeq.XToolkit.Common/Extensions/EnumerableExtensions.cs
Softeq.XToolkit.Common/Extensions/ListExtensions.cs
Softeq.XToolkit.WhiteLabel.Droid/DroidBootstrapperBase.cs
Softeq.XToolkit.WhiteLabel.Droid/MainApplicationBase.cs
Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj
Softeq.XToolkit.WhiteLabel.iOS/AppDelegateBase.cs
Softeq.XToolkit.WhiteLabel.iOS/IosBootstraperBase.cs
Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj
Softeq.XToolkit.WhiteLabel/Bootstrapper/BootstrapperBase.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/BootstrapperWithViewModelLookup.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/DefaultViewModelFinder.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/IBootstrapper.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/ViewModelFinderBase.cs
Softeq.XToolkit.WhiteLabel/Dependencies.cs
Softeq.XToolkit.WhiteLabel/Extensions/ReflectionExtensions.cs
Softeq.XToolkit.WhiteLabel/Mvvm/ViewModelBase.cs
Softeq.XToolkit.Whitelabel.Tests/Bootstrapper/DefaultViewModelFinderTests/DefaultViewModelFinderTests.cs
Softeq.XToolkit.Whitelabel.Tests/Bootstrapper/DefaultViewModelFinderTests/TypeStubs.cs
samples/Playground/Playground.Droid/CustomDroidBootstrapper.cs
samples/Playground/Playground.Droid/MainApplication.cs
samples/Playground/Playground.iOS/AppDelegate.cs
samples/Playground/Playground.iOS/CustomIosBootstraper.cs

The new definition of `Boostraper`:
- Describing WhiteLabel setup
- Contains declarations for setup:
- Assemblies
- External dependencies
- Internal dependencies
- Internal auto-registrations
- WhiteLabel runtime
Features:
- Clean `AppDelegateBase`, `MainApplicationBase`;
- Remove duplicated logic;
- Simple integration and setup for the new projects;
- Ready for Xamarin.Forms integration;
- Auto-register view models can be simply disabled;
Changed:
- `class DroidBootstrapper` -> `abstract class DroidBootstrapperBase`
- `class IosBootstrapper` -> `abstract class IosBootstrapperBase` 
- `IBootstrapper.Init(IList<Assembly>)` -> `IBootstrapper.Initialize()`
- `MainApplicationBase.SelectAssemblies` -> `DroidBootstrapperBase.SelectAssemblies`
- `AppDelegateBase.SelectAssemblies` -> …

Rework boostrappers

---

Softeq.XToolkit.WhiteLabel.iOS/IosPlatformProvider.cs

OnUIThreadAsync fixed - deadlock removed, instant invocation added for the case it's already the main thread
- iOS

OnUIThreadAsync fixed

---

Softeq.XToolkit.PushNotifications.Droid/Softeq.XToolkit.PushNotifications.Droid.csproj
Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj
nuget/Softeq.XToolkit.PushNotifications.nuspec
nuget/Softeq.XToolkit.WhiteLabel.nuspec
samples/Playground/Playground.Droid/Playground.Droid.csproj

Packages:
- Xamarin.AndroidX.Lifecycle.Process: 2.1.0 -> 2.2.0
- Xamarin.Google.Android.Material: 1.1.0-rc2 -> 1.1.0-rc3
None
- Android
None
Not applicable

Update AndroidX nugets

---

Softeq.XToolkit.Common.Tests/Extensions/StreamExtensionsTests/StreamToArrayTests.cs
Softeq.XToolkit.Common/Extensions/StreamExtensions.cs

Added:
- `StreamExtensions.ToArray(Stream)`
None

Add Stream.ToArray method

---

Softeq.XToolkit.Common/Extensions/ListExtensions.cs

Makeing List<T> extensions more versatile by accepting IEnumerable<T> parameters
Changed:
- void AddRange<T>(this IList<T> items, IList<T> range) => void AddRange<T>(this IList<T> items, IEnumerable<T> range)
- void InsertRange<T>(this IList<T> items, int index, IList<T> range) => void InsertRange<T>(this IList<T> items, int index, IEnumerable<T> range)
None
Not applicable

Make list extensions more versatile

---

nuget/Softeq.XToolkit.Bindings.nuspec
nuget/Softeq.XToolkit.Common.nuspec
nuget/Softeq.XToolkit.PushNotifications.nuspec
nuget/Softeq.XToolkit.Remote.nuspec
nuget/Softeq.XToolkit.WhiteLabel.nuspec
samples/Playground/Playground.Droid/Playground.Droid.csproj
samples/Playground/Playground.iOS/Playground.iOS.csproj
samples/Playground/Playground/Playground.csproj

New beta release XToolkit components.
Main changes: 🚀
- AndroidX
Changes: https://github.com/Softeq/XToolkit.WhiteLabel/compare/v2.0.0-beta4...8fc0941148c8fe60214d171bacf27b7c32c36218
- Implemented unified GetHashCode method with null-values support (#253)
- Added Stream.ToArray method (#278)
- Made list extensions more versatile (#279)
- Added method for set command with dispose (#269)
- Added Bindings.Tests
- Added Enum key support for TabNavigation (#242)
- Refactored bootstrapper (#260)
- Reworked dialogs (#272)
- Fixed iOS 13 navigation (#214)
- Fixed OnUIThreadAsync deadlock (#273)
- Updated documentation (#250)
- Updated pipelines versions (#262)
- Share common build properties (#266)
- Resolve nullable warnings (#262, #267, #277) 
- Update GitHub templates (#264)
- Core (all …

New beta version 5

---

Softeq.XToolkit.Common/Helpers/HashHelper.cs

Mark HashHelper class as obsolete in favor of using System.HashCode
Changed:
- static class HashHelper marked as obsolete with justification

Mark HashHelper as obsolete

---

Softeq.XToolkit.Bindings.Tests/AssertHelpers.cs
Softeq.XToolkit.Bindings.Tests/BindingExtensionsTests/BindingExtensionsTests.cs
Softeq.XToolkit.Bindings/BindingExtensions.cs

Reported by @Synthezator 
Case:
```cs
view.SetCommand(nameof(view.SomeGenericEvent),
new RelayCommand<EventArgs>(x => {})); <- runtime exception
```
Workaround:
```cs
view.SetCommand<EventArgs>(nameof(view.SomeGenericEvent),
new RelayCommand<EventArgs>(x => {}));
```
- `SetCommand<TEventArgs>` only for `ICommand<TEventArgs>`
None
Not applicable

Constraint of SetCommand methods for TEventArgs

---

README.md
azure-pipelines/nuget-Softeq.XToolkit.WhiteLabel.Essentials.yml
azure-pipelines/nuget-Softeq.XToolkit.WhiteLabel.Forms.yml
documentation/articles/developer-guide.md
documentation/articles/intro.md
nuget/Softeq.XToolkit.Bindings.nuspec
nuget/Softeq.XToolkit.Common.nuspec
nuget/Softeq.XToolkit.Permissions.nuspec
nuget/Softeq.XToolkit.PushNotifications.nuspec
nuget/Softeq.XToolkit.Remote.nuspec
nuget/Softeq.XToolkit.WhiteLabel.Essentials.nuspec
nuget/Softeq.XToolkit.WhiteLabel.Essentials.sln
nuget/Softeq.XToolkit.WhiteLabel.Forms.nuspec
nuget/Softeq.XToolkit.WhiteLabel.Forms.sln
nuget/Softeq.XToolkit.WhiteLabel.nuspec

New beta release XToolkit components.
Main changes: 🚀
- Xamarin.Forms
Changes: https://github.com/Softeq/XToolkit.WhiteLabel/compare/v2.0.0-beta5...aae6f948676edae2caf657f913c7d1da17191edf
- Mark HashHelper as obsolete (#283)
- Weak delegates refactoring (#289)
- Refactored extensions (#290)
- Rework AsyncCommand (#293)
- Constraint of SetCommand methods for TEventArgs (#287)
- ImagePicker migrated to WhiteLabel.Essentials (#258)
- Remove dependency on Permissions for WhiteLabel (#294)
- `IPermissionRequestHandler` moved to `Softeq.XToolkit.Common.Droid.Permissions.IPermissionRequestHandler` (#258)
- Added support XF (#258)
- Add some converters and controls to WhiteLabel.Forms (#291)
- Generic root frame navigation (#292) 
- Update DocFX (286)
- Added `samples/Playground.Forms`
- …

New beta version 6

---

Softeq.XToolkit.Common.Tests/Commands/AsyncCommandTests/AsyncCommandGenericTests.cs
Softeq.XToolkit.Common.Tests/Commands/AsyncCommandTests/AsyncCommandTests.cs
Softeq.XToolkit.Common/Commands/AsyncCommand.cs
Softeq.XToolkit.Common/Commands/AsyncCommandGeneric.cs

Added tests for explicit check resolving constructors for AsyncCommands.

Add tests for resolving async command ctors

---

Softeq.XToolkit.Common/Extensions/EnumExtensions.cs
samples/Playground/Playground.iOS/Playground.iOS.csproj
samples/Playground/Playground.iOS/ViewControllers/Collections/CompositionalLayout/AdaptiveSectionsViewController.cs
samples/Playground/Playground.iOS/ViewControllers/Collections/CompositionalLayout/NSUtils.cs
samples/Playground/Playground.iOS/ViewControllers/Collections/CompositionalLayout/NestedGroupsViewController.cs
samples/Playground/Playground.iOS/ViewControllers/Collections/CompositionalLayoutPageStoryboard.storyboard
samples/Playground/Playground.iOS/ViewControllers/Collections/CompositionalLayoutPageViewController.cs
samples/Playground/Playground.iOS/ViewControllers/Collections/CompositionalLayoutPageViewController.designer.cs
samples/Playground/Playground.iOS/ViewControllers/Collections/GroupedListPageViewController.cs
samples/Playground/Playground.iOS/Views/Collections/DummyCell.cs
samples/Playground/Playground.iOS/Views/Collections/DummyCell.designer.cs
samples/Playground/Playground.iOS/Views/Collections/DummyCell.xib
samples/Playground/Playground.iOS/Views/Table/GroupedTableHeaderView.cs
samples/Playground/Playground/ViewModels/Collections/CompositionalLayoutPageViewModel.cs
samples/Playground/Playground/ViewModels/MainPageViewModel.cs

Added two samples of using Compositional Layout in iOS 13.
- [Apple Sources](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views/using_collection_view_compositional_layouts_and_diffable_data_sources)
- [Swift sample](https://github.com/TikhonovAlexander/Collection-View-Layout-iOS13)
- [Compositional Layout in iOS 13. Fundamental](https://habr.com/ru/post/495076/)
Added:
- `EnumExtensions.FindByValue<TEnum>(byte value)` - Get enumeration that corresponding value.
- Added `Enum` constraint to `EnumExtensions` generic methods.
- iOS

Playground sample: iOS13 Compositional Layout

---

Softeq.XToolkit.WhiteLabel.iOS/Helpers/AvatarImageHelpers.cs

Added new property to configure TextColor for draw Avatar placeholder image.
Added:
- UIColor AvatarImageHelpers.AvatarStyles.TextColor
- iOS

Feature/ios avatar styles - add text color

---

Softeq.XToolkit.WhiteLabel.Droid/MainApplicationBase.cs
Softeq.XToolkit.WhiteLabel.Forms/FormsApp.cs
Softeq.XToolkit.WhiteLabel.iOS/AppDelegateBase.cs
Softeq.XToolkit.WhiteLabel/AssemblySource.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainerBuilder.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/BootstrapperBase.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerBuilder.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/IBootstrapper.cs
samples/Playground.Forms/Playground.Forms/App.xaml.cs
samples/Playground.Forms/Playground.Forms/ViewModels/MainPageViewModel.cs
samples/Playground/Playground.Droid/MainApplication.cs
samples/Playground/Playground.iOS/AppDelegate.cs

Make IBootstrapper stateless IoC container builder. Add callback with initialized container for AppDelegate and MainApplication
Added:
- `void virtual MainApplicationBase.OnContainerInitialized(IContainer)`;
- `void virtual AppDelegateBase.OnContainerInitialized(IContainer)`;
Changed:
- `void IBootstrapper.Initialize()` => `IContainer IBootstrapper.Initialize()`;
- `IBootstrapper MainApplicationBase.Bootstrapper {get;}` => `IBootstrapper MainApplicationBase.CreateBootstrapper()`;
- `IBootstrapper AppDelegateBase.Bootstrapper {get;}` => `IBootstrapper AppDelegateBase.CreateBootstrapper()`;
- iOS
- Android
None
Not applicable

Rework Bootstrapper responsibility and application initialization lifecycle

---

Softeq.XToolkit.Common/Commands/AsyncCommandBase.cs

Case:
When AsyncCommand used with Xamarin.Forms Command binding (Button, etc), XF executes Command in UI thread and internal XF subscription on CanExecute event need that CanExecute was called from a called thread.
The previous implementation was losing the context after execution.
As a result NS exception.
None
- iOS

Fix base async command execution

---

Softeq.XToolkit.Common.Tests/Extensions/DictionaryExtensionsTests/DictionaryExtensionsTests.cs
Softeq.XToolkit.Common/Extensions/DictionaryExtensions.cs
Softeq.XToolkit.WhiteLabel/AssemblySource.cs

Removed `GetValueOrDefault`. Please use [System.Collections.Generic.CollectionExtensions.GetValueOrDefault](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.getvalueordefault)
Added tests.
Removed:
DictionaryExtensions:
- TValue GetValueOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key)

Refactor common dictionary extensions

---

Softeq.XToolkit.Common.iOS/Extensions/UIViewExtensions.cs

Ability to add a border to the custom edges:
```cs
testView
.WithBorder(8, UIColor.Red.CGColor, UIRectEdge.Left)
.WithBorder(8, UIColor.Blue.CGColor, UIRectEdge.Top | UIRectEdge.Bottom);
```
Added:
- UIView UIView.WithBorder(this UIView view, nfloat borderWidth, CGColor borderColor, UIRectEdge edge)
- iOS

Add custom borders with support AutoLayout

---

Softeq.XToolkit.WhiteLabel.Droid/Navigation/DroidFrameNavigationService.cs
Softeq.XToolkit.WhiteLabel.Droid/Navigation/FrameNavigationConfig.cs
Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj
Softeq.XToolkit.WhiteLabel.Droid/ViewComponents/BottomNavigationComponentBase.cs
Softeq.XToolkit.WhiteLabel.Droid/ViewComponents/ToolbarComponent.cs
samples/Playground/Playground.Droid/Views/BottomTabs/BottomTabsPageActivity.cs

Use separate FragmentManagers for each FrameNavigationService instance
Added:
- class FrameNavigationConfig(FragmentManager fragmentManager, int containerId);
Changed:
- DroidFrameNavigationService.Initialize(object) now expect instance of FrameNavigationConfig as parameter;
- Android

Use custom FragmentManager for FrameNavigationService

---

Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DialogFragmentBase.cs

Fixes casting issue on DialogFragment creation
None
- Android

Fix casting issue

---

Softeq.XToolkit.WhiteLabel.iOS/AppDelegateBase.cs
XToolkit.ruleset
documentation/articles/configure-android.md
documentation/articles/configure-ios.md
samples/Playground/Playground.iOS/AppDelegate.cs

Added several methods to hide details of navigation init implementation and avoid boilerplate in each project.
Added protected methods to AppDelegateBase:
- UINavigationController CreateRootViewController()
- void InitializeMainWindow(UIViewController rootViewController)
- void InitializeNavigation(IContainer container)
- iOS

Hide details of iOS init navigation

---

Softeq.XToolkit.Common.Tests/Collections/ObservableItemContentRangeCollectionTests/ObservableItemContentRangeCollectionDataProvider.cs
Softeq.XToolkit.Common.Tests/Collections/ObservableItemContentRangeCollectionTests/ObservableItemContentRangeCollectionTests.cs
Softeq.XToolkit.Common.Tests/ObservableObjectTests/ObservableObjectTests.cs
Softeq.XToolkit.Common.Tests/ObservableObjectTests/Utils/CustomAsserts.cs
Softeq.XToolkit.Common/Collections/ObservableItemContentRangeCollection.cs

Tests for ObservableItemContentRangeCollection
None
None
Not applicable

Tests for ObservableItemContentRangeCollection

---

Softeq.XToolkit.Common.iOS.Tests/Extensions/UIColorExtensionsTests/UIColorExtensionsTests.cs
Softeq.XToolkit.Common.iOS.Tests/Softeq.XToolkit.Common.iOS.Tests.csproj
Softeq.XToolkit.Common.iOS/Extensions/UIColorExtensions.cs

Tests added
- Fixes `UIColorExtensions.ToHex`
- iOS

Add UIColorExtensions tests

---

Softeq.XToolkit.Common.Tests/Extensions/StringExtensionsTests/StringExtensionsTests.cs
Softeq.XToolkit.Common.iOS.Tests/Extensions/NSStringExtensions/NSStringExtensionsTests.cs
Softeq.XToolkit.Common.iOS/Extensions/NSStringExtensions.cs
Softeq.XToolkit.Common/Extensions/StringExtensions.cs

- Add handle `example.com`, `www.example.com` links.
Consistently to Android: https://developer.android.com/reference/android/text/util/Linkify
None
- iOS

Improve links detection

---

Softeq.XToolkit.WhiteLabel.Droid/Navigation/BackPressedCallback.cs
Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj
Softeq.XToolkit.WhiteLabel.Droid/Views/ToolbarFragmentBase.cs

Move BackPressedCallback to a separate file as a public class
Added:
- public class BackPressedCallback
- Android
None
Not applicable

Make BackPressedCallback public

---

Softeq.XToolkit.WhiteLabel.Tests/Model/TabItemTests/TabItemTests.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainer.cs
Softeq.XToolkit.WhiteLabel/Model/DialogType.cs
Softeq.XToolkit.WhiteLabel/Model/OpenDialogOptions.cs
Softeq.XToolkit.WhiteLabel/Model/TabItem.cs

Tests and documentation for TabItem added
None
None
Not applicable

Tests and documentation for TabItem

---

Softeq.XToolkit.Bindings.Droid/Bindable/BindableRecyclerViewAdapter.cs

Headers and footers are now automatically countered in ItemCount
- Android
None

Headers and footers are now automatically countered in ItemCount

---

Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DroidFragmentDialogService.cs
Softeq.XToolkit.WhiteLabel.Tests/Bootstrapper/Containers/DryIocContainerAdapterTests/DryIocContainerAdapterTests.cs
Softeq.XToolkit.WhiteLabel.Tests/Bootstrapper/Containers/DryIocContainerAdapterTests/DryIocContainerAdapterTestsDataProvider.cs
Softeq.XToolkit.WhiteLabel.Tests/Bootstrapper/Containers/DryIocContainerBuilderTests/DryIocContainerBuilderTests.cs
Softeq.XToolkit.WhiteLabel.Tests/Bootstrapper/DefaultViewModelFinderTests/DefaultViewModelFinderTests.cs
Softeq.XToolkit.WhiteLabel.Tests/Dialogs/ActionSheetDialogConfigTests/ActionSheetDialogConfigTests.cs
Softeq.XToolkit.WhiteLabel.Tests/Dialogs/AlertDialogConfigTests/AlertDialogConfigTests.cs
Softeq.XToolkit.WhiteLabel.Tests/Dialogs/ConfirmDialogConfigTests/ConfirmDialogConfigTests.cs
Softeq.XToolkit.WhiteLabel.Tests/Stubs/TypeStubs.cs
Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardDialogsService.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainerBuilder.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/BootstrapperBase.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerAdapter.cs
Softeq.XToolkit.WhiteLabel/Dialogs/ActionSheetDialogConfig.cs
Softeq.XToolkit.WhiteLabel/Dialogs/AlertDialogConfig.cs
Softeq.XToolkit.WhiteLabel/Dialogs/ConfirmDialogConfig.cs
Softeq.XToolkit.WhiteLabel/Dialogs/IDialog.cs
samples/Playground/Playground/ViewModels/Dialogs/DialogsPageViewModel.cs

- Tests and documentation added for dialog configs;
- Tests and documentation added for DryIocContainerAdapter;
- Documentation for BootstrapperBase and ContainerBuilder reworked;
DialogConfig classes are now immutable and throw exceptions when initialized with incorrect values.
None
Not applicable

DialogConfigs and DryIocContainerAdapter tests

---

Softeq.XToolkit.WhiteLabel.Droid/ActivityBase.cs
Softeq.XToolkit.WhiteLabel.Tests/Mvvm/CommandActionTests/CommandActionTests.cs
Softeq.XToolkit.WhiteLabel.Tests/Navigation/BackStackManagerTests/BackStackManagerTests.cs
Softeq.XToolkit.WhiteLabel.Tests/Navigation/BackStackManagerTests/BackStackManagerTestsDataProvider.cs
Softeq.XToolkit.WhiteLabel/Dependencies.cs
Softeq.XToolkit.WhiteLabel/Navigation/BackStackManager.cs
Softeq.XToolkit.WhiteLabel/Navigation/IBackStackManager.cs
Softeq.XToolkit.WhiteLabel/Navigation/PageNavigationService.cs

- Tests and documentation for BackStackManager added
- Documentation for Dependencies added
Added:
- IViewModelBase BackStackManager.PeekViewModel();
- bool BackStackManager.TryPeekViewModel(out IViewModelBase);
- bool BackStackManager.TryPopViewModel(out IViewModelBase);
Removed:
- TViewModel BackStackManager.GetExistingOrCreateViewModel<TViewModel>() where TViewModel : IViewModelBase;
None
Not applicable

Tests and documentation for BackStackManager

---

Softeq.XToolkit.WhiteLabel.Tests/Stubs/MainThreadExecutorBaseStub.cs
Softeq.XToolkit.WhiteLabel.Tests/ViewModels/PaginationSearchViewModelBaseTests/PaginationSearchViewModelBaseTests.cs
Softeq.XToolkit.WhiteLabel.Tests/ViewModels/PaginationSearchViewModelBaseTests/TestPaginationSearchViewModelBaseTests.cs
Softeq.XToolkit.WhiteLabel.Tests/ViewModels/PaginationViewModelBaseTests/PaginationViewModelBaseTests.cs
Softeq.XToolkit.WhiteLabel.Tests/ViewModels/PaginationViewModelBaseTests/TestPaginationViewModelBase.cs
Softeq.XToolkit.WhiteLabel/Model/PagingModel.cs
Softeq.XToolkit.WhiteLabel/ViewModels/PaginationSearchViewModelBase.cs
Softeq.XToolkit.WhiteLabel/ViewModels/PaginationViewModelBase.cs
samples/Playground.Forms/Playground.Forms/CoreBootstrapper.cs
samples/Playground.Forms/Playground.Forms/ViewModels/Components/PaginationSearchPageViewModel.cs
samples/Playground.Forms/Playground.Forms/ViewModels/MainPageViewModel.cs
samples/Playground.Forms/Playground.Forms/Views/Components/PaginationSearchPage.xaml
samples/Playground.Forms/Playground.Forms/Views/Components/PaginationSearchPage.xaml.cs
samples/Playground.Forms/Playground.Forms/Views/MainPage.xaml
samples/Playground/Playground/ViewModels/MainPageViewModel.cs

Add tests
Add docs
Add Playground.Forms sample
Rework Playground.Forms MainPage
- `PaginationSearchViewModelBase.SearchQuery` behavior for an empty value
Changed:
- `PaginationViewModelBase.LoadAsync(int pageNumber, int pageSize)` -> abstract
- `ICommand LoadMoreCommand` -> `IAsyncCommand LoadMoreCommand`
None

Add tests for pagination view models

---

Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DialogFragmentBase.cs
Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DroidFragmentDialogService.cs
Softeq.XToolkit.WhiteLabel.Droid/Dialogs/IDialogFragment.cs
Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj

Add ability to override showing dialog on Android
`DialogFragmentBase` now implements an interface `IDialogFragment`
Added:
- event EventHandler? IDialogFragment.Dismissed;
- void IDialogFragment.Show ();
- Android
None
Not applicable

Android: Add ability to override showing dialog

---

Softeq.XToolkit.WhiteLabel.Droid/Navigation/DroidFrameNavigationService.cs
Softeq.XToolkit.WhiteLabel.Droid/Views/ToolbarFragmentBase.cs

Allow to go back with one screen in backstack of DroidFrameNavigationService to clear backstack
None
- Android
None
Not applicable

Android: allow to go back with one item to clear backstack

---

Softeq.XToolkit.WhiteLabel.Droid/Dialogs/DialogFragmentBase.cs

Clearing DataContext removed from DialogFragmentBase.
This is done because `OnDismiss` method may be called both before and after `OnViewDisappeared`.
If `OnDismiss` is called after `OnViewDisappeared`, then Dismissed event is not raised.
Moving clearing DataContext to `OnDismiss` is not an option because in that case there will be another problem:
If `OnDismiss` is called before `OnViewDisappeared`(and other lifecycle methods like `OnPause`) then we can't call `OnDisappearing()` method on the ViewModel.
None
- Android
None
Not applicable

Clearing DataContext removed from DialogFragmentBase

---

Softeq.XToolkit.PushNotifications.Droid/DroidPushNotificationParser.cs

Use real push notification title and message if the resource (loaded by title or message localization key) is not available
None
- Android
None
Not applicable

Push Notification Parser fix

---

Softeq.XToolkit.PushNotifications.Droid/NotificationIntentActivityInfo.cs
Softeq.XToolkit.PushNotifications.Droid/NotificationsHelper.cs

Add ability to provide flags to Push Notification intent on Android (including No flags). By default no flags will be supplied now (previously the following flags were used: `ActivityFlags.NewTask | ActivityFlags.ClearTask`)
Added:
- ActivityFlags? Flags { get; set; } to `NotificationIntentActivityInfo`
Changed:
- NotificationIntentActivityInfo(Type activityType, bool doCreateParentStack)
=> NotificationIntentActivityInfo(Type activityType, bool doCreateParentStack, ActivityFlags? flags = null)
- Android
None
Not applicable

Android foreground notifications intent

---

Softeq.XToolkit.Permissions.Droid/PermissionsService.cs
Softeq.XToolkit.Permissions.iOS/PermissionsService.cs

Request permissions on the main thread internally.
None
- iOS
- Android
No more need for additional main thread wrappers to work with permissions.
Not applicable

Thread safe permissions

---

Softeq.XToolkit.WhiteLabel.Droid/Services/LocationService.cs

LocationService now requests location on UI thread internally. Previously it caused crash if called from background thread
None
- Android
None
Not applicable

Request location on UI thread

---

Softeq.XToolkit.WhiteLabel.Droid/FragmentBase.cs

Calling base.OnCreate moved to be the last call in OnCreate (after restoring and initializing ViewModel)
None
- Android
None
Not applicable

BaseFragment OnCreate fix

---

Softeq.XToolkit.WhiteLabel.Droid/Internal/ViewModelStore.cs

Add ability to setup ViewModelStore for a FragmentManager
Added:
- void ViewModelStore.SetupFor(FragmentManager)
- Android
None
Not applicable

Add public method for ViewModelStore setup

---

Softeq.XToolkit.Permissions.iOS/Softeq.XToolkit.Permissions.iOS.csproj
Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj

NuGets were updated (Xamarin.Essentials) to remove warnings
- iOS

NuGets warnings resolved

---

Softeq.XToolkit.Common.iOS/Extensions/NSStringExtensions.cs

Added ability to customize the font of links in UITextAreas
Added:
- LinksFont(this NSMutableAttributedString self, UIFont font)
- iOS
None
Not applicable

Added customizing the font of links

---

Softeq.XToolkit.Bindings.iOS/ObservableCollectionViewSource.cs
Softeq.XToolkit.Bindings.iOS/ObservableTableViewSource.cs

Add handling of Move case, so that collection items could be sorted with animation when calling ObservableCollectionExtensions.Sort.
Made methods from UITableView and UICollectionView the same.
None
- iOS
None
Not applicable

Added handling of items movement in a UICollectionView

---

Softeq.XToolkit.WhiteLabel.Droid/FragmentBase.cs
Softeq.XToolkit.WhiteLabel.Droid/Internal/BackStack.cs
Softeq.XToolkit.WhiteLabel.Droid/Internal/ViewModelStore.cs
Softeq.XToolkit.WhiteLabel.Droid/Navigation/DroidFrameNavigationService.cs
Softeq.XToolkit.WhiteLabel.iOS/Navigation/StoryboardFrameNavigationService.cs
Softeq.XToolkit.WhiteLabel/Navigation/IFrameNavigationService.cs

This update separates back-stack handling and `FragmentManager` manipulations within `DroidFrameNavigationSerivice`. This makes it possible to update ViewModelStore only when actual navigation is happening.
- fixes "InvalidOperationException: View Model store has been destroyed", which happened when app tries to perform navigation actions in background
Removed:
- `void IFrameNavigationService.RestoreUnfinishedNavigation()` - now it's automatically handled by `RestoreNavigation()`
- Android
None
Not applicable

Update ViewModelStore only when actual navigation is happening

---

Softeq.XToolkit.Bindings.Droid/Bindable/BindableRecyclerViewAdapter.cs
samples/Playground/Playground.Droid/Views/Collections/GroupedCollectionPageActivity.cs
samples/Playground/Playground.Droid/Views/Collections/GroupedTablePageActivity.cs

BindableRecyclerViewAdapter didn't have option to initialize HeaderSectionViewHolder and FooterSectionViewHolder in construction. 
None
- Android
None
Not applicable

Parameters added to BindableRecyclerViewAdapter constructor

---

Softeq.XToolkit.Connectivity.iOS/IosConnectivityService.cs
Softeq.XToolkit.Connectivity/ConnectivityService.cs
Softeq.XToolkit.Connectivity/IConnectivityService.cs

Replace custom delegates with EventHandler pattern
Changed:
- `ConnectivityChangedEventHandler IConnectivityService.ConnectivityChanged` => `EventHandler<ConnectivityChangedEventArgs> IConnectivityService.ConnectivityChanged`
- `ConnectivityTypeChangedEventHandler ConnectivityTypeChanged` => `EventHandler<ConnectivityTypeChangedEventArgs> ConnectivityTypeChanged`
None

Replace custom delegates with EventHandler pattern

---

Softeq.XToolkit.WhiteLabel.Droid/Services/DroidLauncherService.cs
Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj
Softeq.XToolkit.WhiteLabel.iOS/Services/IosLauncherService.cs
Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj
Softeq.XToolkit.WhiteLabel/Interfaces/ILauncherService.cs
Softeq.XToolkit.WhiteLabel/Services/EssentialsLauncherService.cs
samples/Playground.Forms/Playground.Forms.Droid/DroidBootstrapper.cs
samples/Playground.Forms/Playground.Forms.Droid/Playground.Forms.Droid.csproj
samples/Playground.Forms/Playground.Forms.iOS/IosBootstrapper.cs
samples/Playground.Forms/Playground.Forms.iOS/Playground.Forms.iOS.csproj
samples/Playground.Forms/Playground.Forms/CoreBootstrapper.cs
samples/Playground.Forms/Playground.Forms/ViewModels/Components/LauncherPageViewModel.cs
samples/Playground.Forms/Playground.Forms/ViewModels/MainPageViewModel.cs
samples/Playground.Forms/Playground.Forms/Views/Components/LauncherPage.xaml
samples/Playground.Forms/Playground.Forms/Views/Components/LauncherPage.xaml.cs
samples/Playground/Playground.Droid/Playground.Droid.csproj
samples/Playground/Playground.iOS/Playground.iOS.csproj

Previous apps are compatible with changes except for the removed method.
New apps may be able to use `EssentialsLauncherService` implementation directly in the core project or use extended platform-specific implementations as before.
- fixes #237
- fixes #297
Added:
- WhiteLabel.Services.EssentialsLauncherService
Changed:
- WhiteLabel.Droid.Services.**LauncherService** => WhiteLabel.Droid.Services.**DroidLauncherService**
- WhiteLabel.iOS.Services.**LauncherService** => WhiteLabel.iOS.Services.**IosLauncherService**
Removed:
- void ILaucherService.OpenDeviceSecuritySettings()
- iOS
- Android
None
Not applicable

Rework LauncherServices to use Xamarin.Essentials

---

Softeq.XToolkit.Bindings.Droid/DroidBinding.cs
Softeq.XToolkit.Bindings.Droid/DroidBindingFactory.cs
Softeq.XToolkit.Bindings.iOS/AppleBinding.cs
Softeq.XToolkit.Bindings.iOS/AppleBindingFactory.cs
Softeq.XToolkit.Bindings/Binding.cs
Softeq.XToolkit.Bindings/BindingExtensions.cs
Softeq.XToolkit.Bindings/BindingFactoryBase.cs
Softeq.XToolkit.Bindings/BindingGeneric.cs
Softeq.XToolkit.Bindings/Extensions/BindableExtensions.cs
Softeq.XToolkit.Bindings/IBindingFactory.cs
Softeq.XToolkit.Bindings/UpdateTriggerMode.cs

Enable nullability for:
- `BindingGeneric`
- `AppleBinding`
- `DroidBinding`
- `BindingExtesnions`
- `BaseBindingFactory`
- `AppleBindingFactory`
- `DroidBindingFactory`
Added more docs.
- Reviewed. It's OK by design. Closes #268 
- Added more docs for #447 
None
- iOS
- Android
None
Not applicable

Enable nullability for Bindings primitives

---

samples/Playground.Forms/Playground.Forms.Droid/DroidBootstrapper.cs
samples/Playground.Forms/Playground.Forms.Droid/Playground.Forms.Droid.csproj

Sync Playground.Droid:
- Resolve conflict between Google.Android.Material from Xamarin.Forms (latest) and WL.Droid (old stable)

Sync Playground.Droid for MaterialDesign 1.4

---

Softeq.XToolkit.WhiteLabel.iOS/Services/StoryboardDialogsService.cs

It is possible that the controller that presented the dialog has been removed from the navigation stack, so calling `DismissViewController` on it will not close the previously shown dialog. ~~We can call `DismissViewController` on the shown `ViewController` and `UIKit` will do all the work for us~~ (as it turned out, not always - in the case if the dismiss controller, that presented another one, then it will not dismiss itself, but the presented one)
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismiss
None
- iOS
None
Before
After

Fix closing ios dialogs

---

Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainer.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Abstract/IContainerBuilder.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerAdapter.cs
Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerBuilder.cs

1. `DryIocContainerBuilder` class did not have a method for registering service by service key.
2. `DryIocContainerAdapter` class did not have a method for resolving service by service key.
1. Method for registering service by service key as singleton in the `DryIocContainerBuilder`.
2. Method for resolving service by service key in the `DryIocContainerAdapter`.

Add registration and resolving by service key

---

Softeq.XToolkit.Permissions.Droid/PermissionsManager.cs

- fixes #
- PermissionManager.CheckAsync<T>
- Android
None
Not applicable

Permission manager changed

---

Softeq.XToolkit.PushNotifications.Droid/NotificationsHelper.cs

In android 12 Pending Intent should have Mutable or Immutable flag. Immutable choose because intent is not changed and it's recommended to use immutable if possible 
Added:
- Immutable flag
- Android

pending intent fixed

---

Softeq.XToolkit.WhiteLabel/Bootstrapper/Containers/DryIocContainerBuilder.cs

Add `WithUseInterpretation` rule for fix crash on iOS.
Added:
- `protected virtual Rules DryIocContainerBuilder.CreateContainerRules()`
Not applicable

Expose rules to configure container outside

---

Softeq.XToolkit.Common/Weak/WeakDelegate.cs

Adds a conditional (DEBUG-only) assertion for cases, when weak delegates are used with potentially risky lambda expressions. Warning message will be propagated to the Debug Console if the target if the delegate is non-static class with `[CompilerGenerated]` attribute, specifically:
- if lambda has only static references. In this case compiler generates a singleton class, which is never garbage collected, so it is more of a false alarm;
- if lambda has some references to local variables. In this case compiler generates a class and creates an instance of this class, never keeping any hard reference to it - so it might be garbage collected at any moment.
None
None
Not applicable

Conditional Assert to warn about compiler-generated targets

---

Softeq.XToolkit.WhiteLabel.Droid/Navigation/DroidFrameNavigationService.cs

Calling `executePendingTransaction` if we want to swap two fragments will very quickly lead to an `IllegalStateException: FragmentManager is already executing transactions`, so it should be removed. It looks like just calling `commit`, although asynchronous, won't cause problems, since each `commit` is queued and executed when the main thread is ready
[docs](https://developer.android.com/reference/androidx/fragment/app/FragmentTransaction#commit())
None
- Android
None
Not applicable

Removed executePendingTransaction call from the navigation service

---

Softeq.XToolkit.PushNotifications.Droid/Abstract/IDroidFirebaseMessagingHandler.cs
Softeq.XToolkit.PushNotifications.Droid/Services/DroidPushNotificationsConsumer.cs
Softeq.XToolkit.PushNotifications.Droid/Services/DroidPushNotificationsService.cs
Softeq.XToolkit.PushNotifications.Droid/Softeq.XToolkit.PushNotifications.Droid.csproj
Softeq.XToolkit.PushNotifications.Droid/XFirebaseMessagingService.cs

Now, when we close the Android app and send a silent notification (where `notification = null`) it will not be handled because the `OnNotificationReceived` delegate will be `null`, since no one will create/resolve the `DroidPushNotificationsService`. Since the `FirebaseMessagingService` is recreated if the app is closed, I simply added getting the `DroidPushNotificationsService` from the container since the container is also created since the `Android.App.Application` object is created when the `FirebaseMessagingService` is recreated
None
- Android
None
Not applicable

Fixed handling of silent push notifications on Android

---

Softeq.XToolkit.Remote.Tests/Client/HttpMessageHandlerProviderTests.cs
Softeq.XToolkit.Remote/Client/DefaultHttpMessageHandlerBuilder.cs
Softeq.XToolkit.Remote/Client/HttpMessageHandlerProvider.cs

Now, if we go in to get a new HttpMessageHandler for another HttpClient, we get the same HttpMessageHandler. And if HttpClient is disposed, then HttpMessageHandler will also be disposed, which will make other HttpClients not work
Added:
- bool HttpMessageHandlerProvider.CreateOrGetCachedDefaultHandler()
Changed:
- bool HttpMessageHandlerProvider.CreateDefaultHandler()
None
Not applicable

Implemented differents methods for creating and caching HttpMessageHandler

---

Softeq.XToolkit.WhiteLabel.iOS/Services/IosLocationService.cs

- fixes #
None
- iOS
- Android
None
Not applicable

add possibility to get CLLocationManager outside

---

Softeq.XToolkit.WhiteLabel/Location/LocationModel.cs

Add IEquatable for LocationModel

---

Softeq.XToolkit.Permissions.Droid/PermissionsManager.cs
Softeq.XToolkit.Permissions.iOS/Permissions/Bluetooth.cs
Softeq.XToolkit.Permissions.iOS/Permissions/Notifications.cs
Softeq.XToolkit.Permissions.iOS/PermissionsManager.cs

- Fixed warnings regarding recent changes to the permissions library.
None
- iOS
- Android
None
Not applicable

Refactor permissions library

---

Softeq.XToolkit.Bindings.Droid/Softeq.XToolkit.Bindings.Droid.csproj
Softeq.XToolkit.Bindings.iOS/Softeq.XToolkit.Bindings.iOS.csproj
Softeq.XToolkit.Common.Droid.Tests/Softeq.XToolkit.Common.Droid.Tests.csproj
Softeq.XToolkit.Common.Droid/Softeq.XToolkit.Common.Droid.csproj
Softeq.XToolkit.Common.iOS/Softeq.XToolkit.Common.iOS.csproj
Softeq.XToolkit.Connectivity.iOS/Softeq.XToolkit.Connectivity.iOS.csproj
Softeq.XToolkit.Permissions.Droid/Softeq.XToolkit.Permissions.Droid.csproj
Softeq.XToolkit.Permissions.iOS/Softeq.XToolkit.Permissions.iOS.csproj
Softeq.XToolkit.PushNotifications.Droid/Softeq.XToolkit.PushNotifications.Droid.csproj
Softeq.XToolkit.PushNotifications.iOS/Softeq.XToolkit.PushNotifications.iOS.csproj
Softeq.XToolkit.WhiteLabel.Droid/Softeq.XToolkit.WhiteLabel.Droid.csproj
Softeq.XToolkit.WhiteLabel.Essentials.Droid/Softeq.XToolkit.WhiteLabel.Essentials.Droid.csproj
Softeq.XToolkit.WhiteLabel.Essentials.iOS/Softeq.XToolkit.WhiteLabel.Essentials.iOS.csproj
Softeq.XToolkit.WhiteLabel.iOS/Softeq.XToolkit.WhiteLabel.iOS.csproj
azure-pipelines/XToolkit.yml
nuget/Softeq.XToolkit.Bindings.nuspec
nuget/Softeq.XToolkit.Common.nuspec
nuget/Softeq.XToolkit.Permissions.nuspec
nuget/Softeq.XToolkit.PushNotifications.nuspec
nuget/Softeq.XToolkit.Remote.nuspec
nuget/Softeq.XToolkit.WhiteLabel.Essentials.nuspec
nuget/Softeq.XToolkit.WhiteLabel.Forms.nuspec
nuget/Softeq.XToolkit.WhiteLabel.nuspec

- Add `SupportedOSPlatformVersion` for packages
- Update nuspecs
- Sync target frameworks 
None
- iOS
- Android
None
Not applicable

Improvements before migration to .NET8
